config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :goals
  resources :comments
  resources :members, except: [:firstVisit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#home'
  get 'about', to: 'welcome#about'


  get 'signup', to: 'members#signup'
  # TODO 新規入会者の時の以下の有効化
  post 'signup', to: 'members#firstVisit'

  get 'goal-list', to: 'goals#goalList'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  # get 'logout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'

end

app/models/goal.rb
class Goal < ApplicationRecord
	belongs_to :member
	validates :member_id, presence: true
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]
  before_action :require_member, except: [:index, :show]
  before_action :require_same_member, only: [:edit, :update, :destroy]

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.paginate(page: params[:page], per_page: 2)
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # GET /goal-list
  def goalList
    @goals = Goal.paginate(page: params[:page], per_page: 2)
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:title, :description, :progress_value, :goal_value, :member_id)
    end

    def require_same_member
      if current_member != @comment.member
        flash[:danger] = "You can only edit or delete your own comments"
        redirect_to root_path
      end
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= form_with(model: goal, local: true) do |form| %>
  <% if goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :goal_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :goal_description %>
  </div>

  <div class="field">
    <%= form.label :progress_value %>
    <%= form.number_field(:progress_value, in: 1.0..100.0, step: 1.0) %>
  </div>

  <div class="field">
    <%= form.label :goal_value %>
    <%= form.number_field(:goal_value, in: 1.0..100.0, step: 1.0) %>
  </div>

  <div class="field">
    <%= form.label :member_id %>
    <%= form.text_field :member_id, id: :member_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/goals/_goal.html.erb
<% obj.each do |goal| %>
  <div class="row center">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
      	<ul class="listing">
			    <div class="row">
			      <div class="col-xs-8 col-xs-offset-2">
			        <div class="well-lg">
			          <div class="name"> 
			            <li><%= link_to gravatar_for(goal.member), member_path(goal.member) %></li>
			            <li class="name"><%= link_to goal.member.name, member_path(goal.member) %></li>
			            <li><small><%= pluralize(goal.member.goals.count, "goal") if goal.member.goals %></small></li>
			          </div>
			        </div>
			      </div>
			    </div>
			  </ul>
        <div class="title"> 
          <%= link_to goal.title, goal_path(goal) %>
        </div>
        <div class="description">
          <%= truncate(goal.description, length: 100) %>
        </div>
        <div class="kgi">Current KGI : 
          <%= goal.progress_value %>
        </div>
        <div class="kgi">Goal KGI : 
          <%= goal.goal_value %>
        </div>
        <div class="meta-details">
          <small>Created by: <%= goal.member.name if goal.member %>,
            <%= time_ago_in_words(goal.created_at) %> ago,
            last updated: <%= time_ago_in_words(goal.updated_at) %>
          </small>
        </div>
        <div class="actions">
          <% if current_member && current_member == goal.member %>
            <%= link_to 'Edit this goal', edit_goal_path(goal), class: "btn btn-xs btn-primary" %>
            <%= link_to 'Delete this goal', goal_path(goal), method: :delete, data: { confirm: 'Are you sure you want to delete the goal>' }, class: "btn btn-xs btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

<% end %>
<% if logged_in? %>
  <%= link_to 'New Goal', new_goal_path %>
<% end -%>

app/views/goals/edit.html.erb
<h1>Editing Goal</h1>

<%= render 'form', goal: @goal %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

app/views/goals/goalList.html.erb
<h1 align="center">Goal List</h1>
<p id="notice"><%= notice %></p>
<div align="center">
	<%= will_paginate %>
</div>
<%= render 'goal', obj: @goals %>
<div align="center">
	<%= will_paginate %>
</div>

app/views/goals/index.html.erb
<h1 align="center">Goals</h1>
<p id="notice"><%= notice %></p>

<div align="center">
	<%= will_paginate %>
</div>
<%= render 'goal', obj: @goals %>
<div align="center">
	<%= will_paginate %>
</div>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<%= render 'form', goal: @goal %>

<%= link_to 'Back', goals_path %>

app/views/goals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @goal.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @goal.description %>
</p>

<p>
  <strong>Current value:</strong>
  <%= @goal.progress_value %>
</p>

<p>
  <strong>Goal value:</strong>
  <%= @goal.goal_value %>
</p>

<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', goals_path %>