config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :goals
  resources :comments
  resources :members, except: [:firstVisit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#home'
  get 'about', to: 'welcome#about'


  get 'signup', to: 'members#signup'
  # TODO 新規入会者の時の以下の有効化
  post 'signup', to: 'members#firstVisit'

  get 'goal-list', to: 'goals#goalList'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  # get 'logout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'

end

app/models/member.rb
class Member < ApplicationRecord
	has_many :goals
	# before_save { self.mailaddress = mailaddress.downcase }
	validates :name, presence: true, uniqueness: { case_sensitive: false }
	VALID_MAILADDRESS_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :mailaddress, presence: true, uniqueness: { case_sensitive: false },
		format: { with:VALID_MAILADDRESS_REGEX }
	has_many :comments
	has_secure_password
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  before_action :require_member, except: [:index, :show, :signup, :create]
  before_action :require_same_member, only: [:edit, :update, :destroy]


  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])
    @member_goals = @member.goals.paginate(page: params[:page], per_page: 2)
  end

  # GET /members/new
  def new
    @member = Member.new
    @projects = Project.all
  end

  # GET /signup
  def signup
    @member = Member.new
    @projects = Project.all
  end

  # POST /signup
  # TODO 新規入会者来た時はrootへ飛ばす
  def firstVisit
    @member = Member.new(member_params)
    if @member.save
      flash[:success] = "Welcome to KB platform, #{@member.name}!"
      redirect_to root_path
    end
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)
    @projects = Project.all

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :team, :lq, :mailaddress, :password)
    end

    def require_same_member
      if current_member != @member
        flash[:danger] = "You can only edit or delete your own member info"
        redirect_to root_path
      end
    end
end

app/helpers/members_helper.rb
module MembersHelper
	def gravatar_for(member, option = { size: 80})
		gravatar_id = Digest::MD5::hexdigest(member.mailaddress.downcase)
		size = option[:size]
		gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: member.name, class: "img-circle")
		
	end
end

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :member_name %>
  </div>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.number_field :project_id, id: :project_id %>
    <!-- TODO -->
    <%#= select_tag(:project_id, options_from_collection_for_select(@projects, :id, :name)) %>
  </div>

  <div class="field">
    <%= form.label :lq %>
    <%= form.text_field :lq, id: :member_lq %>
  </div>

  <div class="field">
    <%= form.label :mailaddress %>
    <%= form.text_field :mailaddress, id: :member_mailaddress %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :member_password %>
  </div>

  <div class="actions">
    <%= form.submit(@member.new_record? ? "Create Account" : "Update account", class: "btn btn-primary btn-lg") %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">KB Members</h1>

<% @members.each do |member| %>
  <ul class="listing">
    <div class="row center">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
          <div class="name"> 
            <li><%= link_to gravatar_for(member), member_path(member) %></li>
            <li class="name"><%= link_to member.name, member_path(member) %></li>
            <li><small><%= pluralize(member.goals.count, "goal") if member.goals %></small></li>
          </div>
          <div class="team">
            <%= truncate(member.team , length: 100) %>
          </div>
          <div class="lq">LQ : 
            <%= member.lq %>
          </div>
          <div class="profile">Profile : 
            <%= member.profile %>
          </div>
          <!-- <div class="meta-details">
            <small>Created by: <%# = goal.member.name if goal.member %>,
              <%#= time_ago_in_words(goal.created_at) %> ago,
              last updated: <%#= time_ago_in_words(goal.updated_at) %>
            </small>
          </div> -->
          <% if logged_in? && current_member == member %>
            <div class="actions">
              <%= link_to 'Edit profile', edit_member_path(member), class: "btn btn-xs btn-primary" %>
              <%= link_to 'Delete your account', member_path(member), method: :delete, data: { confirm: 'Are you sure you want to delete this account?' }, class: "btn btn-xs btn-danger" %>
            </div>
          <% end -%>
        </div>
      </div>
    </div>
  </ul>

<% end %>
<%= link_to 'New member', new_member_path, class: "btn btn-xs btn-primary" %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="center">Welcome to <%= @member.name %>'s page</h1>

<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
		<%= gravatar_for @member, size: 100 %>
		<div class="actions">
			<% if current_member && current_member == @member %>
				<%= link_to "Edit my profile and setting", edit_member_path(@member), class: "btn btn-xs btn-primary" %>
				<%= link_to "Delete this account", member_path(@member), method: :delete,
					 data: { confirm: "Are you sure you want to delete this account>"}, 
					 class: "btn btn-xs btn-danger" %>
			<% end -%>
			<%= link_to "View all members", members_path, class: "btn btn-xs btn-success" %>
		</div>
	</div>
</div>

<h4 class="center"><%= @member.name %>'s goals</h4>
<div align="center">
	<%= will_paginate @member_goals %>
</div>
<%= render 'goals/goal', obj: @member.goals %>
<div align="center">
	<%= will_paginate @member_goals %>
</div>

app/views/members/signup.html.erb
<h1 align="center">Signup for KB platform</h1>

<%= form_with(model: @member, local: true) do |form| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :@member_name %>
  </div>

  <div class="field">
    <%= form.label :project_id %>
    <%#= form.text_field :project_id, id: :project_id %>
    <!-- TODO -->
    <%= select_tag(:project_id, options_from_collection_for_select(@projects, :id, :name)) %>
  </div>

  <div class="field">
    <%= form.label :mailaddress %>
    <%= form.text_field :mailaddress, id: :@member_mailaddress %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :@member_password %>
  </div>

  <div class="actions">
    <%= form.submit "Sign up", class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>